services:
  - type: web
    name: Living Hope Trust
    env: node
    rootDir: .  # Use project root
    buildCommand: |
      cd client && npm install && npm run build
      cd ../server && npm install
    startCommand: node backend/server.js  # Make sure this is correct
