name: Keep Backend Alive

on:
  schedule:
    - cron: "*/1 * * * *" # Every 10 minutes
  workflow_dispatch: # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render backend
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://living-hope-charitable-trust-full-stack.onrender.com)
          echo "Response status: $STATUS_CODE"
